### ISSUE TITLE
Align with SFR1 - Category: Composition - Preview Services

### ISSUE THREAD

**Issue by prjelesi** [Azure/terraform-azurerm-avm-res-devopsinfrastructure-pools#5]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

SInce this service is not GA, please make sure that you align with https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr1---category-composition---preview-services

**Comment by jaredfholgate** [comment]
Thanks, I wasn’t aware of this. We have PG support for this module. It looks like we need to add that message to every variable. Would it make sense in the scenario that a whole service is preview that we add a message once at the top of the read me, rather than repeating for every single variable?

**Comment by prjelesi** [comment]
It is more does customer have support for this service. In most cases preview services are not covered with support. 
Whatever makes sense, and let's align this with specifications.
